// <auto-generated />
using System;
using ClawSharp.Lib.Runtime;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClawSharp.Lib.Runtime
{
    [DbContext(typeof(ClawDbContext))]
    [Migration("20260331074452_UpdateMemoryModel")]
    partial class UpdateMemoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ClawSharp.Lib.Runtime.MemoryChunkEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("MemoryChunks");
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.MessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("BlocksJson")
                        .HasMaxLength(10000000)
                        .HasColumnType("TEXT")
                        .HasColumnName("blocks_json");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000000)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_no");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("turn_id");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId", "SequenceNo");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("ThreadSpaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("thread_space_id");

                    b.Property<string>("WorkspaceRoot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_root");

                    b.HasKey("SessionId");

                    b.HasIndex("ThreadSpaceId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.SessionEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(10000000)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_no");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("turn_id");

                    b.HasKey("EventId");

                    b.HasIndex("SessionId", "SequenceNo");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.ThreadSpaceEntity", b =>
                {
                    b.Property<string>("ThreadSpaceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("thread_space_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("BoundFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("bound_folder_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ThreadSpaceId");

                    b.HasIndex("BoundFolderPath")
                        .IsUnique()
                        .HasFilter("bound_folder_path IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("thread_spaces", (string)null);
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.MessageEntity", b =>
                {
                    b.HasOne("ClawSharp.Lib.Runtime.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.SessionEntity", b =>
                {
                    b.HasOne("ClawSharp.Lib.Runtime.ThreadSpaceEntity", null)
                        .WithMany()
                        .HasForeignKey("ThreadSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClawSharp.Lib.Runtime.SessionEventEntity", b =>
                {
                    b.HasOne("ClawSharp.Lib.Runtime.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
